<?php
$lang = isset($_GET['lang']) && $_GET['lang'] === 'en' ? 'en' : 'fr';

$translations = [
  'fr' => [
    'meta_title' => 'JADI DIGITAL | Vibe coding studio',
    'nav_method' => 'Méthode',
    'nav_deliver' => 'Livrables',
    'nav_work' => 'Travail',
    'nav_contact' => 'Contact',
    'nav_cta' => 'Lancer un build',
    'hero_brand' => 'JADI DIGITAL',
    'hero_title' => 'On code ce que vous ressentez.',
    'hero_sub' => 'Produits digitaux conçus et livrés en vibe coding — rapide, précis, AI-native.',
    'hero_cta' => 'Lancer un build',
    'hero_cta_secondary' => 'Voir le travail',
    'method_tag' => '01 — Méthode',
    'method_title' => 'Brief. Build. Ship.',
    'method_sub' => 'Trois mouvements. Zéro théâtre.',
    'step1_label' => 'Brief',
    'step1_text' => 'On capture l’intention, le ton, les contraintes. Une session, un cadrage net.',
    'step2_label' => 'Build',
    'step2_text' => 'On prototype et on itère en vibe coding — IA dans le flux, craft dans chaque décision.',
    'step3_label' => 'Ship',
    'step3_text' => 'On met en prod. Propre, documenté, prêt à évoluer.',
    'deliver_tag' => '02 — Livrables',
    'deliver_title' => 'Ce qu’on livre',
    'deliver_sub' => 'Du signal au produit live.',
    'deliver_1' => 'Applications web & interfaces',
    'deliver_2' => 'Automatisations & agents IA',
    'deliver_3' => 'MVP → V1 production',
    'deliver_4' => 'Intégrations API & systèmes',
    'work_tag' => '03 — Travail',
    'work_title' => 'Sélection',
    'work_sub' => 'Beaucoup d’exigence.',
    'work_1_title' => 'Talents du Maroc',
    'work_1_meta' => '100% Vibe coding',
    'work_1_text' => 'Marketplace talents & entreprises — full remote, recrutement, mise en relation.',
    'work_1_url' => 'https://talentsdumaroc.com',
    'work_1_cta' => 'Ouvrir le site →',
    'work_1_alt' => 'Capture d’écran de la page d’accueil talentsdumaroc.com',
    'work_1_img' => './img/talentsdumaroc.jpg',
    'work_2_title' => 'MyCopy.digital',
    'work_2_meta' => 'IA · Digital twin',
    'work_2_text' => 'Une IA entraînée pour être vous.',
    'work_2_url' => 'https://mycopy.digital',
    'work_2_cta' => 'Ouvrir le site →',
    'work_2_alt' => 'Capture d’écran de la page d’accueil mycopy.digital',
    'work_2_img' => './img/mycopy.jpg',
    'work_prev' => 'Projet précédent',
    'work_next' => 'Projet suivant',
    'contact_tag' => '04 — Contact',
    'contact_title' => 'Discutons de votre build',
    'contact_sub' => 'Réponse sous 24h. Premier échange gratuit.',
    'form_name' => 'Nom *',
    'form_email' => 'Email *',
    'form_intent' => 'Intention *',
    'form_intent_ph' => 'Ce que vous voulez construire…',
    'form_submit' => 'Envoyer',
    'form_sending' => 'Envoi…',
    'form_ok' => 'Message envoyé.',
    'form_err' => 'Erreur d’envoi.',
    'form_net' => 'Erreur réseau. Réessayez.',
    'footer_line' => 'Ship the vibe. Keep the craft.',
    'footer_copyright' => '© 2026 JADI DIGITAL',
  ],
  'en' => [
    'meta_title' => 'JADI DIGITAL | Vibe coding studio',
    'nav_method' => 'Method',
    'nav_deliver' => 'Deliverables',
    'nav_work' => 'Work',
    'nav_contact' => 'Contact',
    'nav_cta' => 'Start a build',
    'hero_brand' => 'JADI DIGITAL',
    'hero_title' => 'We code what you feel.',
    'hero_sub' => 'Digital products designed and shipped with vibe coding — fast, precise, AI-native.',
    'hero_cta' => 'Start a build',
    'hero_cta_secondary' => 'See the work',
    'method_tag' => '01 — Method',
    'method_title' => 'Brief. Build. Ship.',
    'method_sub' => 'Three moves. Zero theater.',
    'step1_label' => 'Brief',
    'step1_text' => 'We capture intent, tone, constraints. One session, a sharp frame.',
    'step2_label' => 'Build',
    'step2_text' => 'We prototype and iterate with vibe coding — AI in the flow, craft in every call.',
    'step3_label' => 'Ship',
    'step3_text' => 'We go live. Clean, documented, ready to evolve.',
    'deliver_tag' => '02 — Deliverables',
    'deliver_title' => 'What we ship',
    'deliver_sub' => 'From signal to live product.',
    'deliver_1' => 'Web apps & interfaces',
    'deliver_2' => 'Automations & AI agents',
    'deliver_3' => 'MVP → production V1',
    'deliver_4' => 'API & system integrations',
    'work_tag' => '03 — Work',
    'work_title' => 'Selected',
    'work_sub' => 'High bar.',
    'work_1_title' => 'Talents du Maroc',
    'work_1_meta' => '100% Vibe coding',
    'work_1_text' => 'Talent & company marketplace — full remote, hiring, matching.',
    'work_1_url' => 'https://talentsdumaroc.com',
    'work_1_cta' => 'Open site →',
    'work_1_alt' => 'Screenshot of the talentsdumaroc.com homepage',
    'work_1_img' => './img/talentsdumaroc.jpg',
    'work_2_title' => 'MyCopy.digital',
    'work_2_meta' => 'AI · Digital twin',
    'work_2_text' => 'An AI trained to be you.',
    'work_2_url' => 'https://mycopy.digital',
    'work_2_cta' => 'Open site →',
    'work_2_alt' => 'Screenshot of the mycopy.digital homepage',
    'work_2_img' => './img/mycopy.jpg',
    'work_prev' => 'Previous project',
    'work_next' => 'Next project',
    'contact_tag' => '04 — Contact',
    'contact_title' => 'Let’s talk about your build',
    'contact_sub' => 'Reply within 24h. First call is free.',
    'form_name' => 'Name *',
    'form_email' => 'Email *',
    'form_intent' => 'Intent *',
    'form_intent_ph' => 'What you want to build…',
    'form_submit' => 'Send',
    'form_sending' => 'Sending…',
    'form_ok' => 'Message sent.',
    'form_err' => 'Send failed.',
    'form_net' => 'Network error. Try again.',
    'footer_line' => 'Ship the vibe. Keep the craft.',
    'footer_copyright' => '© 2026 JADI DIGITAL',
  ],
];

function __($key)
{
  global $lang, $translations;
  return $translations[$lang][$key] ?? $key;
}

function lang_url($new_lang)
{
  $params = $_GET;
  $params['lang'] = $new_lang;
  return '?' . http_build_query($params);
}
